---
kind: pipeline
name: mon-pipeline

steps:
 
- name: create
  image: lowess/preact-cli
  commands:
    - preact create oytoch/preact-hugo#${DRONE_COMMIT} test
    - cd test
    - npm install
    - npm run build

- name: slack
  image: plugins/slack
  settings:
    webhook: 
      from_secret: slack
    channel: drone-ci
    link_names: true
    image_url: https://cloud.esportconnect.com/avatars/ErlARqzo5fwdXbNktQ7j1368g_g2Xal1IWYQjm7TJz6F94n3MSAUNV8LkthHeouPwy5KfDZcGxBp.jpg
    template: >
      {{#success build.status}}
        build {{build.number}} réussi. Tu vas faire quoi ? Thomas
      {{else}}
        build {{build.number}} failed. Erreur :'(. <@channelname> <@someone>
      {{/success}}

