---
kind: pipeline
name: mon-pipeline

steps:
- name: hello-word
  image: busybox
  commands:
  - echo "hello world"
  - preact create oytoch/preact-hugo  test

steps:
- name: slack
  image: plugins/slack
  settings:
    webhook: 
      from_secret: slack
    channel: dev
    username: drone
    icon_url: https://vignette.wikia.nocookie.net/abolotcho/images/2/2b/Lama_bizarre004.jpg/revision/latest?cb=20140522131715&path-prefix=fr 
    template: >
      {{#success build.status}}
        build {{build.number}} réussi. Tu va faire quoi ?
      {{else}}
        build {{build.number}} failed. Erreur :'(. <@channelname> <@someone>
      {{/success}}